---
- name: Generate Firewall Sync Email Report
  hosts: "{{ workflow_target_host | default('localhost') }}"
  connection: local
  gather_facts: false

  vars:
    report_date: "{{ report_date | default(lookup('pipe', 'date +%Y-%m-%d')) }}"
    report_scope_label: "{{ 'Template Stacks' if (push_scope_type | default('template_stack')) == 'template_stack' else 'Device Groups' }}"

    # Defaults allow this playbook to run standalone; in workflow, pass stats from get_fw_push_status.yml
    scope_sync_details: "{{ scope_sync_details | default({}) }}"
    scopes_out_of_sync: "{{ scopes_out_of_sync | default([]) }}"
    push_scope_changes_summary: "{{ push_scope_changes_summary | default({}) }}"
    push_scope_changes_by_scope: "{{ push_scope_changes_by_scope | default({}) }}"

    owner_counts: "{{ push_scope_changes_summary.owner_counts | default(push_scope_changes_summary.account_counts | default({})) }}"
    objtype_counts: "{{ push_scope_changes_summary.objtype_counts | default({}) }}"

    devices_in_sync_count: >-
      {{
        scope_sync_details
        | dict2items
        | map(attribute='value.connected_in_sync_count')
        | map('default', 0)
        | map('int')
        | sum
      }}
    devices_out_of_sync_count: >-
      {{
        scope_sync_details
        | dict2items
        | map(attribute='value.connected_out_of_sync_count')
        | map('default', 0)
        | map('int')
        | sum
      }}

    report_output_dir: "{{ report_output_dir | default('./reports') }}"
    report_filename_prefix: "{{ report_filename_prefix | default('fw_sync_daily_report') }}"
    report_text_path: "{{ report_output_dir }}/{{ report_filename_prefix }}_{{ report_date }}.txt"
    report_html_path: "{{ report_output_dir }}/{{ report_filename_prefix }}_{{ report_date }}.html"
    report_subject: "{{ report_subject | default('Panorama Daily Sync Report - ' ~ report_date) }}"
    report_emit_html_base64: "{{ report_emit_html_base64 | default(false) | bool }}"
    report_emit_html_debug: "{{ report_emit_html_debug | default(false) | bool }}"

    send_email: "{{ send_email | default(false) | bool }}"
    smtp_host: "{{ smtp_host | default('') }}"
    smtp_port: "{{ smtp_port | default(25) }}"
    smtp_username: "{{ smtp_username | default(omit) }}"
    smtp_password: "{{ smtp_password | default(omit) }}"
    email_from: "{{ email_from | default(omit) }}"
    email_to: "{{ email_to | default([]) }}"
    email_cc: "{{ email_cc | default([]) }}"

  tasks:
    - name: Build per-scope report rows
      ansible.builtin.set_fact:
        report_scope_rows: >-
          {%- set rows = [] -%}
          {%- for scope_name in scopes_out_of_sync -%}
          {%-   set scope_data = push_scope_changes_by_scope.get(scope_name, {}) -%}
          {%-   set entries = scope_data.get('entries', []) -%}
          {%-   set owner_counts_map = {} -%}
          {%-   set objtype_counts_map = {} -%}
          {%-   for entry in entries -%}
          {%-     set owner = (entry.admin | default('') | string | trim) -%}
          {%-     set objtype = (entry.objtype | default('') | string | trim) -%}
          {%-     if owner != '' -%}
          {%-       set _ = owner_counts_map.update({owner: ((owner_counts_map.get(owner, 0) | int) + 1)}) -%}
          {%-     endif -%}
          {%-     if objtype != '' -%}
          {%-       set _ = objtype_counts_map.update({objtype: ((objtype_counts_map.get(objtype, 0) | int) + 1)}) -%}
          {%-     endif -%}
          {%-   endfor -%}
          {%-   set _ = rows.append({
                'scope': scope_name,
                'change_count': (entries | length),
                'owner_counts': owner_counts_map,
                'objtype_counts': objtype_counts_map
              }) -%}
          {%- endfor -%}
          {{ rows }}

    - name: Ensure report output directory exists
      ansible.builtin.file:
        path: "{{ report_output_dir }}"
        state: directory
        mode: "0755"

    - name: Render plain text report
      ansible.builtin.template:
        src: "templates/fw_sync_daily_report.txt.j2"
        dest: "{{ report_text_path }}"
        mode: "0644"

    - name: Render HTML report
      ansible.builtin.template:
        src: "templates/fw_sync_daily_report.html.j2"
        dest: "{{ report_html_path }}"
        mode: "0644"

    - name: Read rendered HTML report as base64
      ansible.builtin.slurp:
        src: "{{ report_html_path }}"
      register: report_html_slurp
      when: report_emit_html_base64 or report_emit_html_debug

    - name: Debug rendered HTML report as base64
      ansible.builtin.debug:
        msg: "{{ report_html_slurp.content }}"
      when:
        - report_emit_html_debug
        - report_html_slurp is defined

    - name: Send report email (HTML)
      ansible.builtin.mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        from: "{{ email_from }}"
        to: "{{ (email_to if (email_to is string) else (email_to | join(','))) }}"
        cc: "{{ (email_cc if (email_cc is string) else (email_cc | join(','))) if (email_cc | length > 0) else omit }}"
        subject: "{{ report_subject }}"
        subtype: html
        body: "{{ lookup('template', 'templates/fw_sync_daily_report.html.j2') }}"
      when:
        - send_email
        - smtp_host | length > 0
        - (email_to is string and (email_to | length > 0)) or (email_to is sequence and (email_to | length > 0))

    - name: Publish report outputs as stats
      ansible.builtin.set_stats:
        data:
          report_date: "{{ report_date }}"
          report_subject: "{{ report_subject }}"
          report_scope_label: "{{ report_scope_label }}"
          report_text_path: "{{ report_text_path }}"
          report_html_path: "{{ report_html_path }}"
          report_scope_rows: "{{ report_scope_rows }}"
          devices_in_sync_count: "{{ devices_in_sync_count }}"
          devices_out_of_sync_count: "{{ devices_out_of_sync_count }}"
          owner_counts: "{{ owner_counts }}"
          objtype_counts: "{{ objtype_counts }}"

    - name: Publish HTML base64 as stats
      ansible.builtin.set_stats:
        data:
          report_html_base64: "{{ report_html_slurp.content }}"
      when:
        - report_emit_html_base64
        - report_html_slurp is defined
