---
- name: Get Firewall Push Status
  hosts: "{{ workflow_target_host }}"
  connection: local
  gather_facts: false

  vars:
    device:
      ip_address: "{{ ip_address }}"
      username: "{{ panorama_username }}"
      password: "{{ panorama_password }}"

    # Expected values: template_stack, device_group
    push_scope_type: "{{ push_scope_type | default('template_stack') }}"

    scope_cfg:
      template_stack:
        detail_bulk_cmd: "show template-stack"
        push_scope_keyword: "template-stack"
        md5_field: "template-md5sum"
      device_group:
        detail_bulk_cmd: "show devicegroups"
        push_scope_keyword: "device-group"
        md5_field: "shared-policy-md5sum"

  collections:
    - paloaltonetworks.panos

  tasks:
    - name: Validate push scope type
      ansible.builtin.assert:
        that:
          - push_scope_type in ['template_stack', 'device_group']
        fail_msg: "Invalid push_scope_type='{{ push_scope_type }}'. Use template_stack or device_group."

    - name: Get bulk scope status (sync info + member devices)
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: "{{ scope_cfg[push_scope_type].detail_bulk_cmd }}"
      register: scope_detail_bulk_raw
      failed_when: false

    - name: Normalize bulk scope stdout into JSON variable
      ansible.builtin.set_fact:
        scope_stdout_json: >-
          {{
            (scope_detail_bulk_raw.stdout | from_json)
            if (scope_detail_bulk_raw.stdout is string)
            else (scope_detail_bulk_raw.stdout | default({}))
          }}

    - name: Normalize scope entries list from JSON
      ansible.builtin.set_fact:
        scope_entries: "{{ [scope_entries_raw] if (scope_entries_raw is mapping) else (scope_entries_raw | default([])) }}"
      vars:
        scope_entries_raw: "{{ scope_stdout_json.response.result.entry | default([]) }}"

    - name: Parse candidate scope names from JSON
      ansible.builtin.set_fact:
        candidate_scope_names: >-
          {%- set names = [] -%}
          {%- for scope in scope_entries -%}
          {%-   set name = (scope.get('name', scope.get('@name', '')) | string | trim) -%}
          {%-   if name != '' -%}
          {%-     set _ = names.append(name) -%}
          {%-   endif -%}
          {%- endfor -%}
          {{ names | unique | sort | list }}

    - name: Build all scope device records from JSON
      ansible.builtin.set_fact:
        all_scope_device_records: >-
          {%- set records = [] -%}
          {%- for scope in scope_entries -%}
          {%-   set scope_name = (scope.get('name', scope.get('@name', '')) | string | trim) -%}
          {%-   set devices_raw = ((scope.devices.entry) if (scope.devices is defined and scope.devices.entry is defined) else []) -%}
          {%-   set devices = ([devices_raw] if (devices_raw is mapping) else (devices_raw | default([]))) -%}
          {%-   for dev in devices -%}
          {%-     set _ = records.append(
                    {
                      'scope': scope_name,
                      'serial': (dev.get('serial', '') | string | trim),
                      'hostname': (dev.get('hostname', '') | string | trim),
                      'connected': (dev.get('connected', '') | string | lower | trim),
                      'md5': (dev.get(scope_cfg[push_scope_type].md5_field, '') | string | trim)
                    }
                  ) -%}
          {%-   endfor -%}
          {%- endfor -%}
          {{ records }}

    - name: Parse connected and disconnected device lists from scope data
      ansible.builtin.set_fact:
        connected_device_serials: >-
          {{
            all_scope_device_records
            | selectattr('connected', 'in', ['yes', 'true', '1'])
            | map(attribute='serial')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}
        disconnected_device_serials: >-
          {{
            all_scope_device_records
            | rejectattr('connected', 'in', ['yes', 'true', '1'])
            | map(attribute='serial')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}

    - name: Debug base parsing
      ansible.builtin.debug:
        msg:
          push_scope_type: "{{ push_scope_type }}"
          scope_count: "{{ candidate_scope_names | length }}"
          scope_names: "{{ candidate_scope_names }}"
          all_scope_device_count: "{{ all_scope_device_records | length }}"
          connected_device_count: "{{ connected_device_serials | length }}"
          disconnected_device_count: "{{ disconnected_device_serials | length }}"

    - name: Initialize scope classification variables
      ansible.builtin.set_fact:
        scopes_with_connected_devices: []
        scopes_with_no_connected_devices: []
        scopes_in_sync: []
        scopes_out_of_sync: []
        scope_sync_details: {}

    - name: Classify scope connectivity and sync state
      ansible.builtin.set_fact:
        scopes_with_connected_devices: >-
          {{
            (
              scopes_with_connected_devices
              + ([item] if (scope_connected_devices | length > 0) else [])
            )
            | unique
            | list
          }}
        scopes_with_no_connected_devices: >-
          {{
            (
              scopes_with_no_connected_devices
              + ([item] if (scope_connected_devices | length == 0) else [])
            )
            | unique
            | list
          }}
        scopes_in_sync: >-
          {{
            (
              scopes_in_sync
              + ([item] if ((scope_connected_devices | length > 0) and (scope_md5_values | unique | length <= 1)) else [])
            )
            | unique
            | list
          }}
        scopes_out_of_sync: >-
          {{
            (
              scopes_out_of_sync
              + ([item] if ((scope_connected_devices | length > 0) and (scope_md5_values | unique | length > 1)) else [])
            )
            | unique
            | list
          }}
        scope_sync_details: >-
          {{
            scope_sync_details
            | combine(
                {
                  item: {
                    'devices_in_scope': scope_devices_in_scope,
                    'device_hostnames_in_scope': scope_device_hostnames,
                    'connected_devices_in_scope': scope_connected_devices,
                    'connected_device_hostnames_in_scope': scope_connected_hostnames,
                    'md5_values_found': scope_md5_values | unique,
                    'is_connected': (scope_connected_devices | length > 0),
                    'is_in_sync': ((scope_connected_devices | length > 0) and (scope_md5_values | unique | length <= 1)),
                    'is_out_of_sync': ((scope_connected_devices | length > 0) and (scope_md5_values | unique | length > 1))
                  }
                },
                recursive=True
              )
          }}
      vars:
        scope_records: "{{ all_scope_device_records | selectattr('scope', 'equalto', item) | list }}"
        scope_devices_in_scope: >-
          {{
            scope_records
            | map(attribute='serial')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}
        scope_device_hostnames: >-
          {{
            scope_records
            | map(attribute='hostname')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}
        scope_connected_records: "{{ scope_records | selectattr('connected', 'in', ['yes', 'true', '1']) | list }}"
        scope_connected_devices: >-
          {{
            scope_connected_records
            | map(attribute='serial')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}
        scope_connected_hostnames: >-
          {{
            scope_connected_records
            | map(attribute='hostname')
            | reject('equalto', '')
            | unique
            | sort
            | list
          }}
        scope_md5_values: >-
          {{
            scope_records
            | map(attribute='md5')
            | reject('equalto', '')
            | unique
            | list
          }}
      loop: "{{ candidate_scope_names }}"
      loop_control:
        label: "{{ item }}"

    - name: Debug scope connectivity and sync buckets
      ansible.builtin.debug:
        msg:
          scopes_with_connected_devices: "{{ scopes_with_connected_devices }}"
          scopes_with_no_connected_devices: "{{ scopes_with_no_connected_devices }}"
          scopes_in_sync: "{{ scopes_in_sync }}"
          scopes_out_of_sync: "{{ scopes_out_of_sync }}"
          scope_sync_details: "{{ scope_sync_details }}"

    - name: Run show config push-scope for out-of-sync scopes
      paloaltonetworks.panos.panos_op:
        provider: "{{ device }}"
        cmd: >-
          show config push-scope {{ scope_cfg[push_scope_type].push_scope_keyword }} {{ item }}
      loop: "{{ scopes_out_of_sync }}"
      loop_control:
        label: "{{ item }}"
      register: push_scope_raw
      failed_when: false

    - name: Initialize push scope change tracking
      ansible.builtin.set_fact:
        push_scope_changes_by_scope: {}

    - name: Track xpaths and owners for out-of-sync scopes
      ansible.builtin.set_fact:
        push_scope_changes_by_scope: >-
          {{
            push_scope_changes_by_scope
            | combine(
                {
                  item.item: {
                    'xpaths': parsed_xpaths,
                    'owners': parsed_owners,
                    'raw_output': push_scope_combined
                  }
                },
                recursive=True
              )
          }}
      vars:
        push_scope_combined: "{{ (item.stdout_xml | default('')) ~ '\n' ~ (item.stdout | default('')) }}"
        parsed_xpaths: >-
          {{
            (
              push_scope_combined
              | regex_findall('(?im)(/[A-Za-z0-9_\-\[\]@="\'/:.]+)')
            )
            | map('trim')
            | reject('equalto', '')
            | unique
            | list
          }}
        parsed_owners: >-
          {{
            (
              push_scope_combined
              | regex_findall('(?im)(?:by|user|admin|owner)\\s*[:=]?\\s*([A-Za-z0-9_.-]+)')
            )
            | map('trim')
            | reject('equalto', '')
            | unique
            | list
          }}
      loop: "{{ push_scope_raw.results | default([]) }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Final debug summary
      ansible.builtin.debug:
        msg:
          push_scope_type: "{{ push_scope_type }}"
          connected_scope_count: "{{ scopes_with_connected_devices | length }}"
          disconnected_scope_count: "{{ scopes_with_no_connected_devices | length }}"
          in_sync_scope_count: "{{ scopes_in_sync | length }}"
          out_of_sync_scope_count: "{{ scopes_out_of_sync | length }}"
          push_scope_changes_by_scope: "{{ push_scope_changes_by_scope }}"
